#+TITLE: Les algorithmes sont-ils neutres ?
#+AUTHOR: Laurent Garnier

#+OPTIONS: toc:t h:2 num:t
#+LATEX_HEADER: \hypersetup{colorlinks = true}


* La lettre
** Salutations
   Bonjour toi,

      tu ne sais peut-être pas ce qu'est un algorithme ? 

 

   Ou alors au contraire tu penses que parce que tu les connais trop
   bien cette question te paraît infondée.


   Il y a quelques jours j'ai fait un petit tour rapide sur la face de
   bouc... ça faisait presque un an que je n'y étais pas allé...


   Et crois-moi, je m'en portais plutôt bien.

 

   Seulement voilà, on m'a partagé [[https://www.franceculture.fr/emissions/la-methode-scientifique/cathy-oneil-pour-une-ethique-des-algorithmes?fbclid=IwAR1NYGNbKTKf0Z5VvWJyhwcfTH0aV0Q86-f1Yn7r4nyyO8TaQcn0W9qSKAg][ça]] !

 
** Point culture
   Cathy O'Neil avec ses cheveux multi-colores (ok je juge, mais en
   général les dégradés de couleurs de ce style sont inversement
   proportionnels au QI qui les porte)... ben malgré ses cheveux
   multi-colores je dois reconnaître qu'elle pose une vraie question
   très pertinente.


   La dame en question est data scientist, elle est passée par le MIT
   et Columbia... bref, elle a quelques connaissances utiles pour
   questionner le sujet.

 
   Son raisonnement rejoint peu ou prou celui de notre Science4All
   national dans sa série sur les [[https://www.youtube.com/watch?v=DrjkjPVf7Bw&list=PLtzmb84AoqRTl0m1b82gVLcGU38miqdrC][IA]].


 
** Analyse
   Tu n'es pas obligé de faire math sup pour comprendre le problème.

 
   Il est rare qu'un individu développe des valeurs radicalement
   différentes de celles de son environnement.

 
   Bien sûr tu peux toujours exhiber des exceptions, mais
   statistiquement (voir Bourdieu) on assiste à des reproductions de
   classes.


 
** Retour au réel
   Il est où le rapport avec les algos ?

 
   Les algorithmes les plus utilisés actuellement (FB, YT, Netflix...)
   sont des algorithmes d'apprentissage automatique.


   Le fameux machine learning ou deep learning revient à entraîner les
   machines à partir de jeux de données choisis par des humains. 


   Et oui, le problème ne vient pas des machines mais des humains qui
   les éduquent directement ou indirectement.

 
   Je vais pas épiloguer ici mais si ça t'intéresse de mieux
   comprendre comment fonctionnent les algorithmes de machine learning
   il suffit de le dire.

** Encouragements

   Dans cette vidéo [[https://youtu.be/YPZvA8NjjuM]] non seulement je
   poursuis la réalisation de mes résolutions mes en plus je te
   propose une petite colle en probabilité.


   Voilà c'est tout pour aujourd'hui (en cadeau bonus en pièce jointe
   je te mets le pdf et le html de la newsletter d'hier). 


   Chaque jour est une occasion de devenir meilleur.

 
** Motivation 

   + Qu'as-tu fait aujourd'hui de mieux qu'hier ? 
     Dis-moi en répondant à ce mail.

   + Qu'est-ce que tu aimerais améliorer dans ta vie ? 
     Dis-moi en répondant à ce mail.

 
** Aide
   Ne lâche pas l'affaire pour tes projets. 

 
   Tu peux réussir à tenir tes résolutions si tu t'en donnes les
   moyens et je peux t'y aider si tu en as envie. 


   Si ça t'intéresse il te suffit de répondre à ce mail pour me faire
   savoir tes disponibilités. 


 

 
** Fin et partage
   C'est tout pour aujourd'hui.

 
   PS : si tu lis cette lettre c'est que tu fais partie de mon club
   privé et du coup tu peux faire un acte généreux en la partageant
   autour de toi (par mail et/ou via les réseaux sociaux et asociaux)
   afin que les personnes qui souhaitent s'améliorer puissent
   s'inscrire en cliquant ici :
   [[http://cours-laurent.systeme.io/investis-en-toi]]

   PPS : s'il y a un sujet que tu aimerais que je traite dis-le en
   répondant à cette lettre.


   N'oublie pas, chaque jour est une occasion de devenir meilleur.

   Chaque jour je travaille pour vous apporter toujours plus de valeur

* Où trouver cette lettre ?
** Sur GitHub  
   1. Celle du jour :
      [[https://emacsfreeman.github.io/ccp/newsletter_02_02_2019.html]]

   2. Celle d'hier :
      [[https://emacsfreeman.github.io/ccp/newsletter_01_02_2019.html]]

** Sur Steemit
   1. Celle du jour :
      [[https://steemit.com/algorithmes/@lgsp/les-algorithmes-sont-ils-neutres]]

   2. Celle d'hieur :
      [[https://steemit.com/newsletter/@lgsp/l-annee-commence-en-fevrier]]

* Les outils de code
** L'outil magique pour faire ça
   + [[https://github.com/marsmining/ox-twbs]]
   + la commande magique : =org-twbs-export-to-html=
   + mes tutos pour faire ses premiers pas avec [[https://www.youtube.com/playlist?list=PLUJNJAesbJGWi3dXmGljFTXCPt-ntQFco][org]] et [[https://www.youtube.com/playlist?list=PLUJNJAesbJGXZHtC_bTUOCwB_qkfbdHpZ][emacs]]
