#+TITLE: Onglets ouverts le samedi 27 avril 2019
#+AUTHOR: Laurent Garnier

* Firefox

  + [[https://developers.google.com/maps/documentation/javascript/error-messages#api-project-map-error][Google Maps Platform JavaScript API]]
  + [[http://bonsaiden.github.io/JavaScript-Garden/]]
  + [[https://repl.it/site/docs/repls/intro]]
  + [[https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor]]
  + [[https://github.com/cs50/lectures]]
  + [[https://docs.cs50.net/2016/fall/notes/10/week10.html]]
  + [[https://developers.google.com/web/tools/chrome-devtools/network/]]
  + [[https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode]]
  + [[https://www.digitalocean.com/community/tutorials/understanding-data-types-in-javascript][Understanding JavaScript Data Types]]
  + [[https://assets.digitalocean.com/books/python/how-to-code-in-python.pdf]]
  + [[https://github.com/1000hz/bootstrap-validator]]
  + [[https://lisatagliaferri.org/]]
  + [[https://www.digitalocean.com/community/tutorials/how-to-use-the-javascript-developer-console][How To Use the JavaScript Developer Console]]
  + [[https://www.youtube.com/channel/UCl0hPcsUmeld49qmWWSQKOg/videos][Source Decoded YouTube]]
  + [[https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Op%25C3%25A9rateurs/L_op%25C3%25A9rateur_conditionnel][L'opérateur conditionnel]]
  + [[https://www.youtube.com/channel/UCW5YeuERMmlnqo4oq8vwUpg/playlists][The Net Ninja YouTube]]
  + [[https://www.youtube.com/user/phpacademy/videos][Codecourse]] YouTube
  + [[https://www.youtube.com/user/thenewboston/about][thenewboston YouTube]]
  + [[https://youtu.be/DZp6rxrtcYw][Hangman from Scratch YouTube]]
  + [[https://www.youtube.com/user/cs50tv/videos][CS50]]
  + [[https://emojipedia.org/]]
  + [[https://www.kirupa.com/html5/emoji.htm]]
  + [[https://medium.freecodecamp.org/a-beginner-friendly-guide-to-unicode-d6d45a903515][A Beginner-Friendly Guide to Unicode]]
  + [[https://www.w3schools.com/charsets/ref_emoji_smileys.asp]]
  + [[https://www.quackit.com/]]
  + [[https://docs.galleria.io/article/15-beginners-guide]]
  + 

Proposer 1 formation Développeur Blockchain
1. HTML
2. CSS
3. JavaScript
4. jQuery
5. Angular
6. Node.js
7. C++
8. Smart Contract Ethereum
9. Nem programming
10. EOS
11. Tokens
12. Crowdsales
13. Airdrops
14. Git
15. Solidity
16. Hyperledger
17. fabric
18. composer
19. Truffle
20. Metamask
21. Geth


#+BEGIN_QUOTE
Dans cette formation nous allons partir de zéro et voir ensemble de nombreuses technologies. Tout d'abord nous commencerons par les technologies du Web 1.0 à savoir HTML, CSS et JavaScript.

Nous verrons également quelques bibliothèques et frameworks pour CSS (Twitter Bootstrap) et JavaScript (jQuery, Angular, React, Node...).

Nous approfondirons ensuite les connaissances fondamentales en JavaScript (avoir suivi la formation JavaScript de Zéro à Héros est un plus). 

Nous passerons ensuite au Web 2.0 avec Node.js qui est un frameworks permettant d'utiliser le langage JavaScript côté serveur. Les gens ayant suivis la formation FSD Node.js seront avantagés mais tout sera étudiés à partir de zéro donc pas d'inquiétude si vous ne connaissez pas encore Node.js.


Ensuite nous étudierons les langages C et C++ (historiquement C++ est le langage qui a été utilisé par Satoshi Nakamoto pour bâtir la blockchain Bitcoin). Cela demandera du temps et de la patience parce que C et C++ sont des langages assez bas niveau (donc proches de la machine) et nécessitent donc pas mal d'efforts.


Avec le langage C++ nous approfondirons les aspects spécifiques de la POO (Programmation Orientée Objet). 

Après avoir bien approfondies les connaissances en C++ il sera temps de s'occuper enfin du Web 3.0 qui est l'objectif majeur de cette formation.

Nous introduirons les spécificités du Web 3.0 et de la programmation décentralisée. Pour ce faire nous étudierons le fonctionnement de Git, outil incontournable du développeur.

Ensuite nous entamerons l'étude des smart contrats Ethereum. Puis on s'occupera des Dapps.

On verra par la suite les tokens, crowdsales et les airdrops.

On poursuivra notre étude en programmant avec la blockchain EOS. EOS est le grand rival d'Ethereum et cela permettra de se différencier des autres formations qui se focalisent uniquement sur Solidity et Ethereum.

Enfin on étudiera Hyperledger Fabric et Composer.

Il est important de participer activement durant toute la formation ce qui signifie entre autre :
de poser des questions à la communauté
de répondre aux questions des autres membres de la communauté
de partager les ressources annexes utiles à l'apprentissage
de travailler en collaboration avec le maximum de membres de la communauté

Cette formation est très longue parce que j'ai décidé de prendre le temps de bien ancrer, décortiquer et analyser les notions en profondeur. 

Au-delà des connaissances, qui sont hélas périssables, c'est plutôt un état d'esprit (mindset en anglais), une vision de la technologie, une vision de l'apprentissage, une vision du monde et une vision des sociétés humaines que je souhaite partager avec celles et ceux qui décideront de prendre leur destin en main en faisant partie intégrante de cette communauté de bâtisseurs.


#+END_QUOTE

+ à 9€ la semaine du 29/04 (S1) 5 pers => 45€
  BONUS: JS0H (valeur 199€)

+ à 18€ la semaine du 6/05 (S2) 5 pers => 90€ (total 10 pers => 135€)
  BONUS: Py0H (valeur 199€)

+ à 36€ la semaine du 13/05 (S3) 5 pers => 180€ (total 15 pers => 315€)
  BONUS: CDBSSR (valeur 199€)

+ à 72€ la semaine du 20/05 (S4) 5 pers => 360€ (total 20 pers => 675€)
  BONUS: ACBP (valeur 199€)

+ à 144€ la semaine du 27/05 (S5) 5 pers => 720€ (total 25 pers => 1395€)
  BONUS: 
  1. JS0H (valeur 199€)
  2. Py0H (valeur 199€)
  Total 199€ + 199€ = 398€ OFFERT !

+ à 288€ la semaine du 3/06 (S6) 5 pers => 1440€ (total 30 pers => 2835€)
  BONUS: 
  1. JS0H (valeur 199€)
  2. Py0H (valeur 199€)
  3. CDBSSR (valeur 199€)
  Total 597€ OFFERT !

+ à 576€ la semaine du 10/06 (S7) 5 pers => 2880€ (total 35 pers => 5715€)
  BONUS: 
  1. JS0H (valeur 199€)
  2. Py0H (valeur 199€)
  3. CDBSSR (valeur 199€)
  4. ACBP (valeur 199€)
  Total 796€

+ à 1152€ la semaine du 17/06 (S8) 5 pers => 5760€ (total 40 pers => 11475€)
  BONUS: 
  1. JS0H (valeur 199€)
  2. Py0H (valeur 199€)
  3. CDBSSR (valeur 199€)
  4. ACBP (valeur 199€)
  5. FSD Node.js (valeur 199€)
  Total 995€ OFFERT !

+ à 2304€ la semaine du 24/06 (S9) 5 pers => 11520€ (total 45 pers => 22995€)
  BONUS: 
  1. JS0H (valeur 199€)
  2. Py0H (valeur 199€)
  3. CDBSSR (valeur 199€)
  4. ACBP (valeur 199€)
  5. FSD Node.js (valeur 199€)
  6. FSD PHP (valeur 199€)
  Total 1194€ OFFERT !

+ à 4608€ la semaine du 1/07 (S10) 
  BONUS: 
  1. JS0H (valeur 199€)
  2. Py0H (valeur 199€)
  3. CDBSSR (valeur 199€)
  4. ACBP (valeur 199€)
  5. FSD Node.js (valeur 199€)
  6. FSD PHP (valeur 199€)
  7. FSD Python (valeur 199€)
  Total 1393€ OFFERT !

+ à 9216€ la semaine du 8/07 (S11)
  BONUS: 
  1. JS0H (valeur 199€)
  2. Py0H (valeur 199€)
  3. CDBSSR (valeur 199€)
  4. ACBP (valeur 199€)
  5. FSD Complet (node, php, python, rails) (valeur 4 x 199€ = 796€)
  Total 1592€ OFFERT !

+ à 18432€ la semaine du 15/07 (S12)
  BONUS: 
  1. JS0H (valeur 199€)
  2. Py0H (valeur 199€)
  3. CDBSSR (valeur 199€)
  4. ACBP (valeur 199€)
  5. FSD Complet (node, php, python, rails) (valeur 4 x 199€ = 796€)
  6. ACBJS (Apprendre à Coder 1 Blockchain avec JS) (valeur 199€)
  Total 1791€ OFFERT !

