#+TITLE: Enregistrer et modifier des informations
#+AUTHOR: Laurent Garnier

* Enregistrer des informations

  Une application doit pouvoir accéder rapidement aux
  informations. Sinon, elles pourraient mettre pas mal de temps à
  réaliser les tâches qui leur sont dévolues. Elles stockent donc ces
  information (ou données) en mémoire. Mais cette mémoire n'est que
  temporaire. Lorsque vous éteignez la machine, il est indispensable
  que vos données soient enregistrées sous une forme permanente, qu'il
  s'agisse de votre disque dure, d'un disque ou d'une clé USB, d'une
  carte mémoire, d'un disque réseau, ou encore d'un nuage Internet. De
  plus, vous devez tenir compte de la nature de ces données, par
  exemple des nombres ou du texte. Les sections qui suivent discutent
  de ces sujets plus en détails. 

** Considérer les variables comme des boîtes de rangement

   Lorsque vous travaillez avec des applications, vous enregistrez des
   informations (ou des données) dans des variables. Une /variable/,
   c'est comme une sorte de boîte de rangement. Lorsque vous voulez
   accéder à une certaine information, vous utilisez la variable qui
   la contient. Si vous avez de nouvelles informations à enregistrer,
   vous les placez dans une variable. Changer des informations
   implique d'accéder d'abord à la bonne variable (la bonne boîte de
   rangement), puis à y enregistrer les nouvelles valeurs. Et vous
   pouvez bien sûr aussi vider une boîte de rangement, et donc
   également une variable. Bref, les variables, c'est comme dans la
   vraie vie.

   Les ordinateurs sont des machines plutôt soigneuses quant au
   rangement des affaires. Chaque variable contient uniquement un
   objet, ou plutôt une pièce d'information particulière, sans avoir à
   fouiller dans les tréfonds d'une gigantesque malle en osier. Vous
   n'avez pas eu à rencontrer de variables dans les précédents
   chapitres, mais sachez que la plupart des applications reposent sur
   une utilisation intensive de boîtes de rangement électroniques.

** Utiliser la bonne boîte pour enregistrer les bonnes données

   Utiliser des variables spécialisées permet de travailler avec leur
   contenu en utilisant des outils spécifiques. 

*** Les entiers   

    #+BEGIN_SRC python
      binaire = 0b100
      print(binaire) # renvoie 4
      octal = 0o100
      print(octal) # renvoie 64
      hexadecimal = 0x100
      print(hexadecimal) # renvoie 256
    #+END_SRC

* Travailler avec des dates et des heures    

  Les dates et les heures sont des données couramment utilisées. Qu'il
  s'agisse d'un rendez-vous, d'un événement quelconque, d'un
  anniversaire ou tout simplement de se réveiller le matin, ce type de
  donnée rythme notre existence. Du fait de cette familiarité avec
  notre vie, il est utile, et même nécessaire, de savoir comment
  Python traite tout cela. Et, comme les ordinateurs ne connaissent
  que des nombres, les dates et les heures n'ont pas plus de sens pour
  eux que les chaînes de caractères.

  Pour travailler avec des dates et des heures, vous devez opérer une
  tâche particulière dans Python. Celui-ci est un peu comme un
  ordinateur, et il ne sait pas de quoi on parle tant que vous n'avez
  pas importé (=import=) un module particulier appelé =datetime=. Mais
  voilà un sujet sur lequel nous reviendrons dans le chapitre 10. Ne
  vous souciez donc pas pour l'instant des tenants et des aboutissants
  de cette commande. Tout ce que vous voulez dans l'immédiat, c'est
  pour pouvoir faire quelque chose avec les dates et les heures.

  Les ordinateurs contiennent des horloges. Mais celles-ci servent
  surtout aux humains qui utilisent l'ordinateur. Tournez le problème
  dans tous les sens, et vous arriverez à la même conclusion... Pour
  obtenir l'heure courante, vous pouvez taper
  =datetime.datetime.now()= suivi d'un appui sur Entrée. 
